### ISSUE TITLE
Issue with inflector when pluralizing word album

### ISSUE THREAD

**Issue by gmanley** [hanami/utils#106]
I'm rebuilding a rails gallery of mine to use lotus and was running into a weird issue where when using:

`resources :albums`

in my routes and then referencing it via `routes.path(:albums)` it was not being recognized as a valid route. I dug into the stacktrace and found the issue to be related to the inflector.

```
Root (1 matchers)
 HttpRouter::Node::Lookup
 when "albums":
   RequestMethod ["GET", "HEAD"] (1 matchers)
    Path: "/albums" for route alba to Albums::Index
```
The route was being named `alba`. Long story short, to reproduce:

```ruby
Lotus::Utils::String.new('albums').singularize # => #<Lotus::Utils::String:0x007fb9ce5135d0 @string="alba">
```

The relevant piece of code is here: https://github.com/lotus/utils/blob/master/lib/lotus/utils/inflector.rb#L356
tracing back to commit: 9e503486 
I'm using master.

I'm working on a PR.

Thanks!

**Comment by jodosha** [comment]
@gmanley Hey thanks for opening this ticket. A PR with the fix is very welcome :+1: 

A side note to let to solve your problem now:

```ruby
Lotus::Utils::Inflector.inflections do
  exception 'album', 'albums'
end

Lotus::Utils::Inflector.pluralize('album') # => "albums"
Lotus::Utils::Inflector.singularize('albums') # => "album"
```
