### ISSUE TITLE
Fix intermittent test

### ISSUE THREAD

**Issue by joneslee85** [hanami/utils#132]
As of https://travis-ci.org/hanami/utils/jobs/117866354, we had one failed test:

```
1) Error:
Hanami::Logger::#initialize::custom stream::file system::when file::and brand new#test_0001_appends to file:
Errno::ENOENT: No such file or directory @ rb_sysopen - tmp/logfile.log
    /home/travis/build/hanami/utils/test/logger_test.rb:131:in `initialize'
    /home/travis/build/hanami/utils/test/logger_test.rb:131:in `new'
    /home/travis/build/hanami/utils/test/logger_test.rb:131:in `block (6 levels) in <top (required)>'
```

This test can be improved to avoid this failure.

**Comment by rogeriozambon** [comment]
Dammit. :disappointed:

I'll try to understand the reason.

**Comment by rogeriozambon** [comment]
While I was reading the tests, I realized that the reason could be the `tmp` folder because it is on .gitignore file. So I made a loop to try find some occurrences and I've found 33 of them.

```shell
for i in {1..100} ; do
  rm -r tmp/ && bundle exec rake test | grep Error ;
done
```

If someone has a workaround to it..

**Comment by davydovanton** [comment]
@rogeriozambon I think I found the problem. I'll send PR soon
