### ISSUE TITLE
BigDecimal in 0.7.1 doesn't handle negative and negative exponents

### ISSUE THREAD

**Issue by RyanHedges** [hanami/utils#140]
Version: Using Hanami 0.7.2 which is using `hanami-utils` 0.7.1.
When trying to coerce a BigDecimal number that would have a negative exponent (`0.09`) or is a negative number(-1.12345), the method raises an error. It was found while trying to create a record with the value of `0.05` in the repository that had a `BigDecimal` mapped to the attribute.

```ruby
describe 'when a negative bigdecimal is given' do
  let(:input) { BigDecimal.new('-12.0001') }

  it 'returns a BigDecimal' do
    @result.must_equal BigDecimal.new('-12.0001')
  end
end

describe 'when the big decimal is less than 1 with high precision' do
  let(:input) { BigDecimal.new('0.0001') }

  it 'returns a BigDecimal' do
    @result.must_equal BigDecimal.new('0.0001')
  end
end
```

These tests fail when checked out on the 0.7.1.

This is because `NUMERIC_MATCHER` doesn't account for `-` in the `to_s` of the passed in `arg`(`-0.120001E2` and `0.1E-3` for example).

Fortunately, the several iterations of `Hanami::Utils::Kernel.BigDecimal` since the 0.7.1 release have fixed this issue (I think it was [this change](https://github.com/hanami/utils/commit/9fb7bcf036e64d7180539c2e2b4b6e2d37e739cb)).

My questions are:
- Would we want to make a `0.7.2` release to fix this issue for current Hanami before `0.8.0` is released?
- Would we want to include these test cases for regression purposes?

**Comment by jodosha** [comment]
@RyanHedges Hey, thanks for reporting this issue.

With https://github.com/hanami/utils/commit/ae1683c00b9404c4ee98f0e632f2b6b6a7ae618a on master we added the tests to prevent regressions.

With https://github.com/hanami/utils/commit/6c8409c995254cc5b5dbe3dca8ea0331cac2d957 we back-ported `Utils::Kernel` from master to 0.7.x

I just released [0.7.2](https://rubygems.org/gems/hanami-utils/versions/0.7.2) with this fix that works fine:

```ruby
[1] pry(main)> require 'hanami/utils/kernel'
true
[2] pry(main)> Hanami::Utils::VERSION
"0.7.2"
[3] pry(main)> Hanami::Utils::Kernel.BigDecimal BigDecimal.new('-12.0001')
-12.0001
```

Happy Friday!
