### ISSUE TITLE
Do we still want to correct the Interactor bit?

### ISSUE THREAD

**Issue by vladdypwnz** [hanami/utils#158]
It's leaving out the fact that it catches and suppresses errors unless specifically defined, `error!()` is different than `error` (collect vs doesn't collect) and that `fail!()` doesn't stop execution. None of them do and none of that is made clear.

I'm not sure of the tone and format of amending an rdoc though so if @cllns could help me out here.

**Comment by cllns** [comment]
Open a PR on this file and change the comments to make them correct :) https://github.com/hanami/utils/blob/master/lib/hanami/interactor.rb I'll help you polish it.

The tone is less casual than the guides, more of 'just the facts', and less narrative-driven. 
For the format, just follow the existing conventions in that file and you should be fine.

**Comment by jodosha** [comment]
@vladdypwnz Hi! If something isn't clear please open a PR to cleanup the API docs. If there is a bug please provide a detailed description of what happens for you. Thanks!

**Comment by jodosha** [comment]
Closing this as stale. @vladdypwnz If you're interested, please reopen and continue the discussion. Thanks.
