### ISSUE TITLE
Use of JSON.load vs JSON.parse

### ISSUE THREAD

**Issue by beauby** [hanami/utils#169]
The ruby docs explicitly say the following
> BEWARE: This method is meant to serialise data from trusted user input, like from your own database server or clients under your control, it could be **dangerous** to allow untrusted users to pass JSON sources into it.

Yet, `load` is used [here](https://github.com/hanami/utils/blob/master/lib/hanami/utils/json.rb), and hanami-router calls that method for parsing json bodies of http requests.

**Comment by AlfonsoUceda** [comment]
@beauby could you open a PR for this? thanks man ;)

**Comment by beauby** [comment]
Not sure what the best way around this is, because `MultiJson` only exposes `#load` (which, when using the std JSON parser via MultiJson, does call `#parse` under the hood), so replacing the `.load` call with `.parse` will not work.

**Comment by beauby** [comment]
Interesting short explanation of the vulnerability introduced by this `JSON#load` call: http://stackoverflow.com/a/30050571/580231

**Comment by cllns** [comment]
If we're using `MultiJson`, which is not vulnerable, let's disable that style rule? (Or, if you're feeling ambitious, submit a patch to Rubocop to check if it's using `MultiJson`)

**Comment by beauby** [comment]
@cllns What "style rule" are you referring to?

**Comment by cllns** [comment]
This one: https://github.com/bbatsov/rubocop/blob/58a70984eea90b78c56e39b31db9bc1ba9a9ce80/config/enabled.yml#L1553-L1561

We can add
```
Security/JSONLoad:
  Enabled: false
```
to `.rubocop.yml` to ignore this rule

**Comment by beauby** [comment]
Oh, I didn't know there was a rubocop rule for that (it is not triggered here though because the call happens indirectly via `@@engine.load`).
The problem is that MultiJson is not necessarily used, which means `::JSON#load` (the vulnerable one) *does* actually get called in that case.
