### ISSUE TITLE
Interactor uses gramatically wrong terms for success/failure

### ISSUE THREAD

**Issue by yjukaku** [hanami/utils#172]
Thank you for your work on this project!

When an Interactor call was a success, we check with either

```ruby
result = Signup.new().call
result.success?
# OR
result.successful?
```

but we check failure with

```ruby
result.failing?
```

This doesn't make grammatic sense, because the opposite of `success?` would be `failure?` and the opposite of `successful?` would still be `failure?`.  However, `failing?` is definitely not correct, because its opposite would be `succeeding?`.

I think this is quite confusing, even though it is a small nitpick.  Maybe `failing?` could be deprecated and aliased to `failure?`?

Thoughts? Thanks again!

**Comment by cllns** [comment]
I agree `failing?` is awkward. I think we should switch it to `failure?`.

`Interactor` just added this convenience method. :sweat_smile: https://github.com/hanami/utils/pull/148.

It looks like the original PR had it as `failure?` but it got switched to `failing?` by @jodosha :)

**Comment by AlfonsoUceda** [comment]
I agree with that change, I think we should use `failure?` instead `failing?`

**Comment by cllns** [comment]
@yjukaku Feel free to open a PR for this change, if you have time :)
