### ISSUE TITLE
Pluralization problems for words ending in -en

### ISSUE THREAD

**Issue by katafrakt** [hanami/utils#173]
I'm using `Kitten` as entity in some of my tests and I was quite surprised when after updating to Hanami 0.9 I found `KittenRepository` complaining that table `kittina` was not present in my database.

I did some digging and found that [this rule](https://github.com/hanami/utils/blob/master/lib/hanami/utils/inflector.rb#L376-L377) is responsible for that. It changes `-en` ending into `-ina` in plural form. I had to do even more digging before I found a hint why it was introduced in the first place. The reason seems to be [some medical terms](http://www.meditec.com/resourcestools/medical-words/medical-plurals/) like `foramen` being `foramina` in plural. However, there are plain English words that are inflected regularly, such as aforementioned `kitten`, `mitten`, `omen` or `abdomen` (actually, `abdomina` is also correct plural form; on the other hand, so is [`foramens`](https://en.wiktionary.org/wiki/foramen#Noun)).

If I were to write a medical app, I would expect the need to set up custom pluralization rules with such words, however I was really surprised when I found that my `Kitten` is not inflected correctly. I would suggest to remove this rule, as it might be confusing for other people too.

**Comment by cllns** [comment]
Thanks for this issue. I agree we should optimize for 🐱  and not `foramen` :) 

Feel free to open a PR for this if you have the time!

**Comment by jodosha** [comment]
Fixed by #174
