### ISSUE TITLE
Error in Hanami::Interactor::Result#respond_to_missing? ?

### ISSUE THREAD

**Issue by pascalbetz** [hanami/utils#183]
`Hanami::Interactor::Result#respond_to_missing?` returns `true` for various concrete methods.

```ruby

      def respond_to_missing?(method_name, _include_all)
        method_name = method_name.to_sym
        METHODS[method_name] || @payload.key?(method_name)
      end
```
https://github.com/hanami/utils/blob/master/lib/hanami/interactor.rb#L144

I don't think that `METHODS[method_name]` should be there.

**Comment by jodosha** [comment]
@pascalbetz It's a [good practice](https://robots.thoughtbot.com/always-define-respond-to-missing-when-overriding) to define `#respond_to_missing?` when `#method_missing` is used.

Being our `Hanami::Interactor::Result` a subclass of `BasicObject`, its behavior it's different from a descendant of `Object`. In our case we want to make sure that this condition is true:

```ruby
result = Hanami::Interactor::Result.new
result.respond_to?(:successful?) # => true
```

For this purpose Ruby VM invokes our `#respond_to_missing?`, which uses `METHODS` as source to understand if a concrete method was defined for that.

Indeed, if we remove `METHODS[method_name]` from there, this test fails: https://github.com/hanami/utils/blob/62c44e6cbb520e8f86ff8b3fd86a5af161cc636e/test/interactor_test.rb#L371

---

> I don't think that `METHODS[method_name]` should be there.

This implementation is confusing, this is the reason why you opened this ticket, **but please** always suggest **actionable** alternative. If you think this should be improved, please open a PR, and let's discuss a new implementation that makes all the tests to pass. :smile: Thank you! :smile:

**Comment by pascalbetz** [comment]
@jodosha 

I totally missed that `Result` is subclassing `Utils::BasicObject` everything makes sense now. Sorry.
