### ISSUE TITLE
[Question] Interactor call with arguments

### ISSUE THREAD

**Issue by alexd16** [hanami/utils#186]
Hi everyone, I have been using the Hanami::Interactor for some time now and I have been wondering if there is a reason on why the call method is not allowed to receive any arguments.

I am asking this because I saw a couple of examples related to testing the Hanami Actions (from the main framework) in the guides and I liked the pattern of injecting dependencies in the constructor and receiving parameters to work on in the call method. But I am not sure if there is a reason on why this is not a good idea to do in the Interactors

Let me know what you think

Thank you

**Comment by jodosha** [comment]
@alexd16 Yes, you're right. I extracted that version of Interactor from a Rails project I was working on two years ago. Because of the lack of DI in Rails, I made the wrong decisions.

That means future versions of Interactor will be DI friendly: `#call` will accept arbitrary arguments.
