### ISSUE TITLE
Migrate from Minitest to RSpec

### ISSUE THREAD

**Issue by jodosha** [hanami/utils#198]
A few rules to follow:

  * If you want to work on this, please leave a comment here. We want to avoid many people to work on the same task.

  * We expect this migration to happen within a week from now.

  * Do not change the tests, only migrate from Minitest to RSpec syntax. If not sure, please ask here.

  * Do not remove the old tests, only add the new ones.

  * Make CI build to use RSpec tests.

  * **Target `develop` branch, instead of `master`.**

  * All the tests artefacts like fixtures, goes under `spec/support`.

  * Try to reflect the structure under `lib/`. Eg. `lib/hanami/view.rb` should be tested under `spec/hanami/view_spec.rb`, while `test/rendering_test.rb` should go under `spec/integration/rendering_spec.rb`.

If you want to take inspiration, please have a look at: https://github.com/hanami/mailer/pull/67

**Comment by artofhuman** [comment]
@jodosha can I take this issue ?

**Comment by jodosha** [comment]
@artofhuman It's all yours. Thank you. 😄
