### ISSUE TITLE
New Hanami::Utils::Interactor::Result-attribute "warnings"

### ISSUE THREAD

**Issue by wuarmin** [hanami/utils#230]
Hello!
What do you think about a new Hanami::Utils::Interactor::Result-attribute "warnings", which can be set/filled with a new Hanami::Utils::Interactor "warning"-method?

To achieve i.e. following:
```ruby
result = CreateRecord.new.call
# result.successful? # => true
# result.errors # => []
# result.warnings # => ["A warning"]
```

We achieve this feature via an custom module, but we would love to use it analogous to error. If you think this could be a feature, I coul provide a PR. 

thanks

**Comment by jodosha** [comment]
@wuarmin What's the semantic of a warning in this case? Is it a warning the comes from a lower level library? Eg. a deprecation warning?

**Comment by wuarmin** [comment]
@jodosha No, I don't mean warnings from lower level libraries. I think of business-logic warnings, which should not affect the status of the result. 

I.e. an interactor, which should prettify a line of an flight-offer.
param of the interactor: 
```
5  LH2349 K 25MAY 5 MUCXKX HK4          2010 2105   *1A/E*
```
success? of the interactor should be true, but with warnings ["Airport IATA-Code 'XKX' is unknown!"]
```
LH2349 Fr, 25. Mai 2018 Munich (MUC) ==> !UNKNOWN! (XKX) 20:10 - 21:05
```
That's just one example. We have other use cases, where we want produce warnings, but the interactor-result should be positive.

**Comment by jodosha** [comment]
@wuarmin What about create your own `warnings` variable and expose it on the outside?

**Comment by wuarmin** [comment]
@jodosha That's what we are doing at several Interactors in our Code-Base. We need to initialize a warnings-variable, write a method analogous to the error-method and expose it. 

In the meantime we tried to write a module which should handle all this, but we were not really happy with it.

I thought other users would also benefit from a warnings-handling.

**Comment by jodosha** [comment]
@wuarmin IMO this looks like a custom need, that I'm happy you found a way to deal with.

Success/failure is a strong dichotomy that can be easily understood because of the binary nature of programming. Adding a third option, would weak it.

**Comment by wuarmin** [comment]
@jodosha ok, I understand.
