### ISSUE TITLE
Idea: Transform classes and modules only with singleton methods into modules with `extend self` or `module_function`.

### ISSUE THREAD

**Issue by serradura** [hanami/utils#240]
Today I read part of the source code looking for the approach used to define static/utility methods.

And I saw two approaches:
1. A class only with public static methods. e.g: [Hanami::Utils::Blank](https://github.com/hanami/utils/blob/v1.1.0/lib/hanami/utils/blank.rb)
2. A module with public and private static methods. e.g: [Hanami::Utils::Files](https://github.com/hanami/utils/blob/a226dc639af0ca083a6d9a44e3d0c09c0805b579/lib/hanami/utils/files.rb)

Ideas for the first approach:
----------------------------

Use a [module with `module_function`](https://idiosyncratic-ruby.com/8-self-improvement.html#modulefunction) instead of a class.

**Benefits:**
1. The API still the same. e.g: `Hanami::Utils::Blank.blank? '    '`
2. The user could include the module in their classes and avoid to typing the module namespaces. e.g:
```ruby
class Person < Struct.new(:name)
  include Hanami::Utils::Blank
  
  def name?
    # Using module_function the methods (filled? and blank?) will be private
    filled? name
  end
end
```

Ideas for the second:
---------------------

Use a [module with `extend self`](https://idiosyncratic-ruby.com/8-self-improvement.html#extend-self)

**Benefits:**
1. Allow to use the private keyword, removing:
  * A [comment](https://github.com/hanami/utils/blob/v1.1.0/lib/hanami/utils/files.rb#L339) to express this group/kind of method.
  * The usage of [`private_class_method`](https://github.com/hanami/utils/blob/v1.1.0/lib/hanami/utils/files.rb#L366) in modules.
2. Allow to create singleton methods without the usage of `self`.

*Note:* You could use `extend self` to the first case, but the module public methods will be public instance methods.

**Comment by jodosha** [comment]
@serradura I've been coming to this issue from time to time. It's a neat idea, but until we don't get a real use case, I'll close it and mark for future consideration.
