### ISSUE TITLE
Proposal: different streams for each level

### ISSUE THREAD

**Issue by davydovanton** [hanami/utils#245]
Just a idea but I think it will be great to have something like this:
```ruby
logger =  Hanami::Logger.new(stream: 'logfile.log', error: { stream: Rollbar.new })
logger.info('Hello') # => put information to logfile
logger.error('Hello') # => put information to rollbar
```

In this case you can use one logger with different sources for each logger level instead using rollbar and logger.

@hanami/core WDYT?

**Comment by AlfonsoUceda** [comment]
Hi @davydovanton I don't this is a good idea, IMO a logger should write in one place, just one. Did you extract this idea from other side?

**Comment by jodosha** [comment]
@davydovanton I'm also with @AlfonsoUceda on this. Having different streams for different levels means to increase drastically the internal complexity of `Hanami::Logger`.

---

I'll give you one example: log file rotation. As of 1.1, you can specify arguments to rotate the log on a time or size metric. Now, the rotation policy is associated with the stream (a file). If we allow multiple streams (files), how can we specify the rotation policy for each of them?

Right now it relies on Ruby's `Logger` (from stdlib). Having multiple streams, means to wrap multiple Ruby's `Logger` or rewrite by our own the rotation policy.

---

This goes beyond the Hanami simplicity. If you have to use multiple log destination (streams) you can use multiple `Hanami::Logger` instances.

**Comment by davydovanton** [comment]
@jodosha yep, agree with your points. And yes, it'll increase complexity for hanami logger 👍 

_P.S.: maybe this idea is a good start for a new ruby gem for different streams_ 🤔
