### ISSUE TITLE
Proposal: inject tags to logger instance

### ISSUE THREAD

**Issue by davydovanton** [hanami/utils#250]
## Why?

We have long logger file with 10k lines. And we want to check what happened for specific request/job execution/etc. 

## How?
We can create simple method `#inject` (we can change name) and use it in any places:

```ruby

Hanami.logger.inject({ ... }) # => new instance of logger

new_logger = Hanami.logger.inject(uuid: uuid)

Hanami.logger.info 'hello' # => 'hello'
new_logger.info 'hello' # => 'uuid="....." hello'
```

For example, we can inject uuid into logger and use it in in rack:

```ruby

class LoggerMiddleware
  def call(env)
    env['logger'] = Hanami.logger.inject(uuid: Secure.uuid)
    [...]
  end
end
```

@hanami/core WDYT?

**Comment by jodosha** [comment]
I like the idea.

**Comment by AlfonsoUceda** [comment]
I like too, what do you think something more explicit?
```
Hanami.logger.tagged(uuid: uuid)
```

**Comment by davydovanton** [comment]
@AlfonsoUceda yep, good idea 👍

**Comment by davydovanton** [comment]
I'll start work on it 👍 

@AlfonsoUceda I think it'll be better to use `with_context` method, like: `Hanami.logger.with_context(uuid: uuid)`. WDYT?

**Comment by AlfonsoUceda** [comment]
@davydovanton 👍

**Comment by jodosha** [comment]
Not actionable right now.
