### ISSUE TITLE
Deprecate `Utils::Class.load_from_pattern!`

### ISSUE THREAD

**Issue by jodosha** [hanami/utils#262]
- [x] Deprecate using `Hanami::Utils::Deprecation` for the purpose
  - [x] Replace all the occurrences in Hanami repositories (`develop` branches) with `Utils::Class.load!`

Use the `develop` branch for this enhancement.

**Comment by oana-sipos** [comment]
Hey @artofhuman! Saw you submitted a PR regarding this issue, may I assign it to you?

**Comment by artofhuman** [comment]
@oana-sipos sure

**Comment by jodosha** [comment]
@artofhuman Thank you very much for your help! 💚
