### ISSUE TITLE
Remove `Utils::Duplicable`

### ISSUE THREAD

**Issue by jodosha** [hanami/utils#265]
- [x] Replace the occurrences of `Utils::Duplicable` with `Object#dup`
  - [x] Remove `Utils::Duplicable`

Use the `unstable` branch for this enhancement.

---

This change should happen **after** we [bumped minimum version of Ruby to 2.4](https://github.com/hanami/hanami/issues/921).

---

Please note, we cannot deprecate `Utils::Duplicable` in `v1.3.0` because we will still support Ruby 2.3 for that version. Ruby 2.3 doesn't have a consistent behavior for `Object#dup`. So if we deprecate, we'll generate tons of annoying warnings that can't be fixed by our users.

**Comment by pawan92** [comment]
i would like to take this on but was initially looking and can't seem to find which file or code this occurs in?

**Comment by cllns** [comment]
@pawan92 Thanks for the help! @jodosha meant [`Hanami::Utils::Duplicable`](https://github.com/hanami/utils/blob/master/lib/hanami/utils/duplicable.rb'), instead of `Hanami::Utils::Duplicate`.

**Comment by cllns** [comment]
_Just fixed the original post and title :)_

**Comment by pawan92** [comment]
got it! just to clarify you say remove `utils::duplicable` and also replace it..? do you want that to be removed and replaced with `Object#dup`

**Comment by cllns** [comment]
Remove the file and replace the instances where it’s used with `Object#dup`. Does that answer your question? Make sure to do it on the `unstable` branch :)

**Comment by pawan92** [comment]
I think so. let me try it out! :)

**Comment by pawan92** [comment]
I think so. let me try it out! :)

**Comment by jodosha** [comment]
@pawan92 thanks for giving it a try.

---

Please note that this will be possible only when the `unstable` branch will be ported to MRI 2.4+ and JRuby 9.2.0.0+. Because these versions of Ruby make `Object#dup` consistent across all the core primitives.

For instance on MRI 2.3 `1.dup` raises an exception, whereas on 2.4+ it works just fine.

---

To recap, we should merge this first: https://github.com/hanami/utils/pull/269 in `unstable`, and then you'll be able to successfully remove `Utils::Duplicable`.

**Comment by jodosha** [comment]
@morron Which version of Ruby?

```ruby
irb(main):001:0> require "complex"
=> false
irb(main):002:0> Complex(1).dup
=> (1+0i)
irb(main):003:0> Rational(1).dup
=> (1/1)
irb(main):004:0> RUBY_VERSION
=> "2.5.1"
```

**Comment by morron** [comment]
@jodosha 
on 2.4

```ruby
pry(main)> Complex(1).dup
TypeError: can't copy Complex
from (pry):2:in `initialize_copy'
pry(main)> RUBY_VERSION
=> "2.4.2"
```

**Comment by jodosha** [comment]
🤦‍♂️ Alright, thanks for spotting this important bit! We'll discuss if to bump directly to 2.5 for Hanami 2.0.

**Comment by jodosha** [comment]
Closed by https://github.com/hanami/utils/pull/322
