### ISSUE TITLE
plural of fee is fees. but Hanami sometimes suggest ves.

### ISSUE THREAD

**Issue by sizer** [hanami/utils#289]
Hi there ;)
I found some strange behaviour of `Hanami::Utils::String.pluralize`.

Should it be better, for being better Hanami ??? 🤔 

## Summary

```
irb(main):003:0> Hanami::Utils::String.pluralize('fee')
=> "fees"
irb(main):004:0> Hanami::Utils::String.pluralize('original_fee')
=> "original_ves"
```

## Description

The plural of `fee` is `fees`. But with prefix, the plural will be `ves`.
It is incorrect behaviour I think... 🤔

**Comment by sakuro** [comment]
[this when clause](https://github.com/hanami/utils/blob/c0f4196bb1b376928d191bb977940366a011a658/lib/hanami/utils/inflector.rb#L385-L386) (rule for knife->knives and such, I think) is the cause?

**Comment by AlfonsoUceda** [comment]
Hi @sizer thanks for this issue, can you try the `Hanami::Utils::Inflector`'s API?
```ruby
Hanami::Utils::Inflector.inflections do
  exception   'original_fee', 'original_fees'
end
```
or try to create a PR if you think you can fix this behaviour

**Comment by jodosha** [comment]
@sizer Thanks for reporting this. I created a fix, would you please review #293 ? Thanks.

**Comment by sizer** [comment]
Hi, @jodosha . Thanks for fixing this. PR is LGTM. I'll try Hanami@1.3.0 👍

**Comment by jodosha** [comment]
Fixed by https://github.com/hanami/utils/pull/293
