### ISSUE TITLE
Logger produces unusable output

### ISSUE THREAD

**Issue by jdickey** [hanami/utils#295]
Calls to reporting methods on `Hanami::Logger` such as `#debug` or `#info` produce output that is at best difficult to read and often obscures values.

Easily-reproducible example (Hanami 1.2.0, `hanami-utils` 1.2.0):

```ruby
$ bin/hanami console
[1] pry(main)> q = {foo: 25, bar: nil, baz: 'What is this?'}
=> {:foo=>25, :bar=>nil, :baz=>"What is this?"}
[2] pry(main)> Hanami::Logger.new.debug(q)
[Hanami] [DEBUG] [2018-08-21 07:28:22 +0000] foo=25=bar==baz=What is this?
=> true
[3] pry(main)> puts q.inspect
{:foo=>25, :bar=>nil, :baz=>"What is this?"}
=> nil
[4] pry(main)> exit
$
```
In discussions with @kaikuchn and @katafrakt earlier today, we tracked down the relevant `Hanami::Logger` code to [this line in `Logger#_format_message`](https://github.com/hanami/utils/blob/master/lib/hanami/logger/formatter.rb#L141) and [this line in `Hanami::Utils::Logger::QueryString`](https://github.com/hanami/utils/blob/master/lib/hanami/utils/query_string.rb#L19). This in turn brings up the question of why logging a Hash is being treated as logging a query string, which none of us could come up with an answer to.

For those who wish to continue using `Hanami::Logger`, I've identified two workarounds:

1. Use `#inspect` within an interpolated string:

```ruby
$ bin/hanami console
[1] pry(main)> q = {foo: 25, bar: nil, baz: 'What is this?'}
=> {:foo=>25, :bar=>nil, :baz=>"What is this?"}
[2] pry(main)> __DUMMY_LINE__=39
=> 39
[3] pry(main)> Hanami::Logger.new.debug("line: #{__DUMMY_LINE__}, q: #{q.inspect}")
[Hanami] [DEBUG] [2018-08-21 12:38:50 +0000] line: 39, q: {:foo=>25, :bar=>nil, :baz=>"What is this?"}
=> true
[4] pry(main)> exit
$
```

2. Use the `params:` parameter with `#debug` and workalikes:

```ruby
$ bin/hanami console
[1] pry(main)> q = {foo: 25, bar: nil, baz: 'What is this?'}
=> {:foo=>25, :bar=>nil, :baz=>"What is this?"}
[2] pry(main)> __DUMMY_LINE__=39
=> 39
[3] pry(main)> Hanami::Logger.new.debug(params: {line: __DUMMY_LINE__, q: q})
[Hanami] [DEBUG] [2018-08-21 12:42:42 +0000] {:line=>39, :q=>{:foo=>25, :bar=>nil, :baz=>"What is this?"}}
=> true
[4] pry(main)> exit
$
```

**Comment by AlfonsoUceda** [comment]
Hi @jdickey as you said this is a bug, besides I've tested in console.

**Comment by AlfonsoUceda** [comment]
Another issue workaround just calling `#to_s`
```ruby
Hanami::Logger.new.debug(q.to_s)
[Hanami] [DEBUG] [2018-09-17 09:42:30 +0200] {:foo=>25, :bar=>nil, :baz=>"What is this?"}
```

**Comment by AlfonsoUceda** [comment]
@jdickey anyway, the problem is that using default formatter is broken for hashes but you can use json formatter and it will be ok.

**Comment by jodosha** [comment]
@jdickey Hi, would you please jump into the fix conversation? Thanks. https://github.com/hanami/utils/pull/297
