### ISSUE TITLE
Feature proposal: Hanami::Utils::String.squish et al

### ISSUE THREAD

**Issue by jdickey** [hanami/utils#298]
## Signature

```ruby
Hanami::Utils::String.squish(input_str)

Hanami::Utils::String#squish
```

## Description

`Hanami::Utils::String.squish` (and its instance-method analogue,  `String#squish`), returns the string, first removing all white-space on both ends of the string, and then changing remaining consecutive white-space groups into one space each.

## Examples

```ruby
  pp str
  # => '<span class="foo">           bar\n              Foo        the\n\tbaz</span>'
  pp Hanami::Utils::String.squish(str)
  # => '<span class="foo">bar Foo the baz</span>'
```

and

```ruby
  s2 = Hanami::Utils::String.new(str)
  # => 'Guillermo            Barranquilla -- the governor of the province --     was in the capital for consultations...and was not expected to return.'
  s2.squish
  # => 'Guillermo Barranquilla -- the governor of the province -- was in the capital for consultations...and was not expected to return.'
```

Note that all consecutive white-space is compressed to a single space, while all _other_ repeated characters are unaffected.

This should take care of the *near totality* of the inadvertent bugs introduced by cavalier use of `String#squeeze` and `String#squeeze!`.

## Prior Art

Ruby on Rails' ActiveSupport library has had a monkey-patch [`String#squish` method](https://github.com/rails/rails/commit/4ff26f51f61f9bf7d0bb34557e72c1280ee4f859) since circa Rails 2.1. It was [proposed](https://bugs.ruby-lang.org/issues/11735) for inclusion into Ruby core in November, 2015, and [shot down](https://bugs.ruby-lang.org/issues/11735#note-13) (on apparent KISS and NIH grounds)  the following June.

**Comment by AMHOL** [comment]
Do you find this useful outside of heredocs? I generally only use it there and find the following syntax much more aesthetically pleasing:

```ruby
str = <<-SQL.strip.gsub(/\s+/, ' ')
  SELECT * FROM "users"
  WHERE "users"."email" = ?
SQL
```

When compared to assigning then calling `Hanami::Utils::String.squish(str)`

**Comment by jdickey** [comment]
I've encountered several bugs in my own code (and specs) where I call `::String#squeeze` expecting it to "clean up" white-space while forgetting that it also removes repeated *non-white-space* characters as well.

```ruby

  s = "     Guillermo         Barranquilla\n"
  # ...
  other_s = s.squeeze
  # => " Guilermo Baranquila\n"
```
Not how Sr. Barranquilla spells his name. 😜 A `#squish` method (which ActiveSupport adds to `::String` and I'm proposing for `Hanami::Utils::String`) would leave the name spelt correctly.

**Comment by jdickey** [comment]
I've removed the `#squish!` method from the original proposal, which originally included the following (without being struck out, of course)

>  ~~The instance method has an "unsafe" analogue, `#squish!`, that performs the operation on the instance on which it is called.~~

Since Hanami favours immutable instances (`Hanami::Utils::String` does not mutate `@string` after `#initialize`), that proposed method has been dropped.

**Comment by kaikuchn** [comment]
Since [squeeze](https://ruby-doc.org/core-2.5.0/String.html#method-i-squeeze) can take the characters it should squeeze as an argument, I don't see much of a need for a `squish` method.

**Comment by jodosha** [comment]
I'm always reluctant to add features here that aren't general purpose (eg. logger, symbolize hash). Especially for `Utils::String`, I don't wanna it to end up as a dump of functionalities.

We added `.transform` to make `Utils::String` open for extension, without the need to implement new transformations:

```ruby
require "hanami/utils/string"
SQUISH = ->(input) { input.gsub(/[[:space:]]+/, " ").strip }
str = "  This\nwas    input with  excess\t\t\twhitespace.      "

Hanami::Utils::String.transform(str, SQUISH)
# => "This was input with excess whitespace."
```

What's the advantage of using `.transform`? You can contact more transformations from: 1. Ruby's `String`, 2. `Utils::String`, 3. Custom transformations (like `SQUISH`).

```ruby
Hanami::Utils::String.transform(str, :underscore, :upcase)
# => "__THIS_WAS____INPUT_WITH__EXCESS___WHITESPACE.______"
```
