### ISSUE TITLE
Utils::Files.append doesn't add properly contents when file doesn't end with a newline

### ISSUE THREAD

**Issue by ttilberg** [hanami/utils#348]
If routes.rb doesn't end with a newline, generate action adds a line with syntax error.

This came up while following the new user guide. Although it should be second nature to have newlines at the end of your files, it's certainly not a requirement in Ruby. While following the guide and copy pasting code, I ended up with a broken routes file after running a generator.

To reproduce:

Edit your routes.rb file to not have a newline, something like 

```
root to: 'home#index'
```

Run a generator:

```
hanami g action web sunshine#index
```

The resulting file is 

```
root to: 'home#index'get '/tires', to: 'sunshine#index'

```

It would be nice if the template generator could detect that the last char.

I tracked the file change back to https://github.com/hanami/utils/blob/master/lib/hanami/utils/files.rb#L162 -- so perhaps it would make more sense to create the issue there instead?

**Comment by jodosha** [comment]
@ttilberg Thanks for trying Hanami and opening an issue. Would you please try if the fix that I just wrote works for you?

To do so:

  1. Edit your `Gemfile` by adding this line: `gem "hanami-utils", git: "https://github.com/hanami/utils.git", branch: "fix/utils-files-append-without-newline"`
  1. Run `bundle update hanami-utils`
  1. Try again to generate a route with `routes.rb` that doesn't end with a newline

**Comment by ttilberg** [comment]
Yes, that patch works as expected: Thanks for being so quick to respond, and with such courtesy.

Two side comments:

- I thought that was a really clever way to test out the fix using the Gemfile to load that patched dependency. For some reason, I don't feel like I've seen that often in bug reports and associated MRs.

- I love how `root to: 'home#index'get '/***tires***', to: '***sunshine***#index'` is now engrained into the associated test haha. I wanted to change boring old tires to something more fun for an issue and forgot to change that word. ;) Oh well, enjoy your sunshine tires ;)

Cheers @jodosha

**Comment by jodosha** [comment]
@ttilberg You made my Friday afternoon better. Thanks!
