### ISSUE TITLE
Boot Error when using postgresql db.

### ISSUE THREAD

**Issue by CryptoRodeo** [hanami/utils#358]
Hello,

So I'm going off the **hanami getting started tutorial** and unless i go with the default sqlite db option i get a boot error.

This is the message i keep getting anytime I run the web server:

**Hanami::Model::Error: undefined method `new' for class `#<Class:BigDecimal>' Did you mean? next**

Nothing was modified except the .env files to connect to the postgresql db.

any hints as to what could be the issue?

thanks!

**Comment by cllns** [comment]
For reference, this was closed because it was in the wrong repo. Here's the right issue: https://github.com/hanami/model/issues/570
