### ISSUE TITLE
hanami-utils libraries are not required by Bundler

### ISSUE THREAD

**Issue by wuarmin** [hanami/utils#360]
Hello,
I use a hanami-utils in a non-hanami-project, and use `Bunder.require`.  However, I have to explicitly call `require 'hanami/utils/UTILS_CLASS'` to be able to use the features. 
Is that the expected behaviour, or should it be fixed?

best regards and thanks

**Comment by jodosha** [comment]
@wuarmin Hey, it's by design. Please have a look at `README`.

> Hanami::Utils is designed to enhance Ruby's code and stdlib. By default this gem doesn't load any code, you must require what you need.

https://github.com/hanami/utils#usage

**Comment by wuarmin** [comment]
Oh, I overlooked that. Thanks!
