### ISSUE TITLE
Make `Hanami::Logger` compatible with `Rack::CommonLogger`

### ISSUE THREAD

**Issue by wuarmin** [hanami/utils#394]
Hey,

I want to improve the requests-logging of my `hanami-api` application and therefore I want to use `Hanami::Logger`, but `Hanami::Logger` needs the `Hanami::CommonLogger`-Rack-middleware, which is not around in pure `hanami-api`-applications. 

Following works, but `Rack::CommonLogger` just calls the `<<` method of `Hanami::Logger`, which results in std ruby logging behavior.
```ruby
use Rack::CommonLogger, Hanami::Logger.new(formatter: Hanami::Logger::JSONFormatter.new)
```

I saw you are working on `dry-logger`. I guess it will be a replacement of `Hanami::Logger`, won't it?

Do you have a hint for me?

Thanks and best regards

**Comment by jodosha** [comment]
@wuarmin Hey, did you had the chance to have a look at it? 😃

**Comment by wuarmin** [comment]
@jodosha hello,
No, I was on parental leave because of my son, but will look at it at the end of the week.
Best regards ;)

**Comment by jodosha** [comment]
@wuarmin Congrats! 👶

**Comment by wuarmin** [comment]
@jodosha Thanks!! ;).

Following code would make `Hanami::Logger` `Rack::CommonLogger`-compatible, 
```ruby
alias :write :info
```
but if we do that, we break following code of `Hanami::CommonLogger`
https://github.com/hanami/hanami/blob/19db85ecb9dcaba7203f49cfdede6bf45e367875/lib/hanami/common_logger.rb#L75

If we do that, we also have to fix `Hanami::CommonLogger` with somethink like this:
```ruby
if logger.respond_to?(:info)
  logger.info(msg)
elsif logger.respond_to?(:write)
  logger.write(msg)
else
  logger << msg
end
```
Do you have an idea?

best regards

**Comment by jodosha** [comment]
Closing as obsolete. We now moved to `dry-logger.`
