### ISSUE TITLE
Interactor

### ISSUE THREAD

**Issue by Nerian** [hanami/utils#401]
Hi,

I see the Interactor module is no longer in hanami-utils 2.0.0.beta1. 
Is it no longer going to be offered? has it been extracted to a different gem? 

Thanks

**Comment by jodosha** [comment]
@Nerian Hey Gonzalo, thanks for asking.

I'm experimenting (in production) with a simple approach based on dry-monads gem.
But that would be outside of hanami-utils.

**Comment by Nerian** [comment]
I see, I have never used dry-monads. Looks like an interesting approach. Although I don't see how that can be used to replace the Interactor pattern itself.

I have 4 apps extensively using the Interactor, I love the simple interface. Is there any chance we can instead extract it to a gem rather than remove it? I can understand you may not want to keep maintaining it in such case I can simply extract it myself and I can maintain it since I do use it. Let me know what you prefer.

**Comment by cllns** [comment]
@Nerian @alistairholt Have you tried out [dry-transaction](https://dry-rb.org/gems/dry-transaction/main/)? (Ignore the warning at the top of the page on the link, it'll be gone soon and dry-transaction will remain). It's a bit like `Hanami::Interactor`, without the learning curve and different paradigm of dry-monads. 

As Hanami we're moving toward consolidating on using **dry-monads** and **dry-transaction**. Specifically, Hanami is focused on the web, while dry-rb is for general purpose libraries. The whole idea behind these interactors/transactions is to be abstracted away from the particulars of the web, so they don't belong in Hanami. It's already a little unwieldy to be supporting two gems that accomplish the same task (in different ways) so I don't think we can consider supporting _three_ gems that do the same thing. Besides, we've used `Hanami::Interactor` in projects and, while it works fine for simple situations, we've seen some of its limitations too.

Feel free to fork and maintain `Hanami::Interactor` (using a different name please, to avoid confusion); it could a be a nice option for people who want to keep their Interactor API's super simple and the learning curve low. But check out dry-transaction first :D

**Comment by alistairholt** [comment]
@cllns I haven't, but it looks interesting. I'll take a look, thank you. Like @Nerian, I really like the standardised & simple interface provided by `Hanami::Interactor` and I'm using it extensively in one of my projects.

**Comment by Nerian** [comment]
@cllns Thanks for the detailed explanation. I took a look at dry-transactions but it seems it has lot more functionality than what I need. Also it seems to me there is no simple migration from Hanami::Interactor to dry-transactions.

I created https://github.com/Nerian/simple-interactors for those like me who would like to keep using Hanami::Interactor.

@alistairholt Please try it out and let me know if you run into any issue. I tested it myself and it worked finely.

Thanks

**Comment by cllns** [comment]
Thanks for doing that @Nerian. In the future if people are looking for the same thing, I'll be sure to direct them to your gem.

What do you think about renaming `Hanami::Interactor` to `SimpleInteractor` inside your gem? It's not a huge deal but it feels a little odd to expose a `Hanami` module in an external project. Then, in the README, you can instruct people to add `Hanami::Interactor = SimpleInteractor` for 100% drop-in backward compatibility. Understand if you want to keep it as-is though.

**Comment by inouire** [comment]
Thanks @Nerian 

@cllns keeping the very same names allows for full reuse of legacy code using hanami interactors, without any patch needed
