### ISSUE TITLE
self check in #blank?

### ISSUE THREAD

**Issue by hi-tech-jazz** [hanami/utils#408]
Shouldn't this be `!object` instead of `!self`? 🤔 

https://github.com/hanami/utils/blob/e8916251c4988331c7ea6fdc1c3ba09009b6d736/lib/hanami/utils/blank.rb#L44

Looks like a copy paste from the ActiveSupport monkeypatch [implementation](https://www.rubydoc.info/gems/activesupport/Object:blank%3F).

**Comment by jodosha** [comment]
@hi-tech-jazz Yes, you're right.
Are you in for a contribution to fix the problem?

Thank you 🙂

**Comment by jodosha** [comment]
Fixed by https://github.com/hanami/utils/pull/409
