### ISSUE TITLE
No published RC1 on RubyGems for utils

### ISSUE THREAD

**Issue by olivierlacan** [hanami/utils#412]
Just noticed this today when attempting to add cli to a Gemfile: 

```
Because every version of hanami-controller depends on hanami-utils ~> 2.1.rc
  and hanami-utils ~> 2.1.rc could not be found in rubygems repository https://rubygems.org/ or installed locally,
  hanami-controller cannot be used.
So, because Gemfile depends on hanami-controller >= 0,
  version solving has failed.
```

I checked and the last released hanami-cli version was 2.1.0.beta1: https://rubygems.org/gems/hanami-utils/versions/2.1.0.beta1

**Comment by olivierlacan** [comment]
Oh you know what, I think that's my fault. 

Since you're probably in the process of changing each gem's dependency in `main` branches, my tracking `main` in my Gemfile is unlikely to work.

**Comment by jodosha** [comment]
@olivierlacan Thanks for reporting. Today we'll release all the gems at rc2 version.
